pool:
  vmImage: 'Ubuntu-16.04'

variables:
  configuration: debug
  platform: x64

steps:
- task: DotNetCoreInstaller@0
  displayName: Install .NET Core SDK
  name: install_dotnetcore_sdk
  enabled: true
  inputs:
    packageType: 'sdk'
    version: '2.2.101'

- script: dotnet tool install -g Wyam.Tool
  displayName: Install Wyam

- script: wyam
  displayName: Build Site

- task: PublishBuildArtifacts@1
  displayName: Publish Site Artifacts 
  inputs:
    pathtoPublish: '$(Agent.BuildDirectory)/s/output'
    artifactName: 'Deployment-$(Build.BuildId)'