languageCode = "en-gb"
title = "Richard Tasker"
baseURL = "https://richardtasker.co.uk"
googleAnalytics = "UA-23137504-1"
paginate = 5

[permalinks]
  posts = "/:year/:month/:day/:title/"

[taxonomies]
  tag = "tags"

[params]
    tag_line = "Strings, Things and Lightsabers"
    description = "Tesla's Awesome Hugo Site"
    recent_posts_number = 5